<project name="SourceDimensions" default="all" basedir=".">

	<!-- Debug flag -->
	<property name="debug" value="true"/>


        <property name="cpptasks.jar" value="${basedir}/ant/lib/cpptasks.jar"/>
	<property name="ant-contrib.jar" value="${basedir}/ant/lib/ant-contrib.jar"/>

	<taskdef resource="cpptasks.tasks">
		<classpath>
			<pathelement location="${cpptasks.jar}"/>
		</classpath>
	</taskdef>

	<typedef resource="cpptasks.types">
		<classpath>
			<pathelement location="${cpptasks.jar}"/>
		</classpath>
	</typedef>

	<taskdef resource="net/sf/antcontrib/antlib.xml">
		<classpath>
			<pathelement location="${ant-contrib.jar}"/>
		</classpath>
	</taskdef>

	<target name="help">
		<echo message="all                - Build all projects"/>
		<echo message="parser.util        - Standalone executable parsing utility"/>
		<echo message="parse.lib          - Shared library of parsing component"/>
		<echo message="parser.tools       - Set of standalone utilities for lexer/parser generation"/>
		<echo message="parser.test.java   - Java parser tests"/>
		<echo message="parser.test.csharp - CSharp parser tests"/>
		<echo message="server.utils       - Profile administration utility and AST Viewer"/>
		<echo message="webservice         - Web Service application"/>
		<echo message="clean              - Cleaning all projects"/>
	</target>

	<target name="init">
		<property name="src.dir" value="${basedir}/src"/>
		<property name="obj.dir" value="${basedir}/obj"/>
		<property name="bin.dir" value="${basedir}/bin"/>

		<if>
			<equals arg1="${debug}" arg2="true" casesensitive="false"/>
			<then>
				<property name="config" value="debug"/>
			</then>
			<else>
				<property name="config" value="release"/>
			</else>
		</if>

		<property name="bin.config.dir" value="${bin.dir}/${config}"/>
		<property name="obj.config.dir" value="${obj.dir}/${config}"/>
	
		<property name="parser.src.dir" value="${src.dir}/parser"/>
		<property name="parser.icu.dir" value="${parser.src.dir}/icu"/>
		<property name="parser.tools.dir" value="${parser.src.dir}/tools"/>
		<property name="parser.test.dir" value="${basedir}/../testsources"/>
		<property name="parser.testoutput.dir" value="${parser.test.dir}"/>

		<property name="jni.common.dir" value="${parser.src.dir}/jni"/>

		<property name="java.source.vm" value="1.5"/>
		<property name="java.target.vm" value="1.5"/>
	
		<property name="backend.src.dir" value="${src.dir}/backend"/>
		<property name="backend.core.dir" value="${backend.src.dir}/core"/>

		<property name="client.src.dir" value="${src.dir}/client/app"/>
	
		<property name="xfire.lib.dir" value="${backend.src.dir}/lib/xfire"/>
		<property name="hibernate.lib.dir" value="${backend.src.dir}/lib/hibernate"/>
		<property name="jdbc.lib.dir" value="${backend.src.dir}/lib/jdbc"/>

		<osfamily property="os.family"/>
		<if> 
			<equals arg1="${os.family}" arg2="windows" casesensitive="false"/>
			<then>
				<property name="os.dir.name" value="win32"/>
				<property name="cc.compiler" value="msvc"/>
				<property name="cc.linker" value="${cc.compiler}"/>
				<property name="cpp.compiler" value="${cc.compiler}"/>
				<property name="cpp.linker" value="${cc.compiler}"/>				
				<property name="icu.os.dir" value="${parser.icu.dir}/win32"/>
				<property name="icu.libs" value="icuuc"/>
				<property name="lib.prefix" value=""/>
				<property name="exec.ext" value=".exe"/>
				<property name="shlib.ext" value=".dll"/>
				<property name="cc.runtime.libtype" value="static"/>
				<property name="jni.os.dir" value="${jni.common.dir}/win32"/>
			</then>
		<elseif> 
			<equals arg1="${os.name}" arg2="linux" casesensitive="false"/>
			<then>
				<property name="os.dir.name" value="linux"/>
				<property name="cc.compiler" value="gcc"/>
				<property name="cc.linker" value="${cc.compiler}"/>
				<property name="cpp.compiler" value="g++"/>
				<property name="cpp.linker" value="${cpp.compiler}"/>				
				<property name="icu.os.dir" value="${parser.icu.dir}/linux"/>
				<property name="icu.libs" value="icuuc34,icudt34"/>
				<property name="lib.prefix" value="lib"/>
				<property name="exec.ext" value=""/>
				<property name="shlib.ext" value=".so"/>
				<property name="cc.runtime.libtype" value="dynamic"/>
				<property name="jni.os.dir" value="${jni.common.dir}/linux"/>
			</then>
		</elseif>
			<else>
				<fail message="Operating system family &quot;${os.family}&quot; is not supported"/>
			</else>	
		</if>

		<property name="parser.bin.dir" value="${bin.config.dir}/parser/${os.dir.name}"/>
		<property name="parser.obj.dir" value="${obj.config.dir}/parser/${os.dir.name}"/>
		
		<property name="tools.bin.dir" value="${parser.bin.dir}/tools"/>
		<property name="tools.obj.dir" value="${parser.obj.dir}/tools"/>		
		
		<property name="backend.dir" value="${obj.config.dir}/backend"/>
		<property name="backend.bin.dir" value="${backend.dir}/lib"/>
		<property name="backend.class.dir" value="${backend.dir}/classes"/>

		<property name="icu.include.dir" value="${parser.icu.dir}/${os.dir.name}/include"/>
		<property name="icu.lib.dir" value="${parser.icu.dir}/${os.dir.name}/lib"/>

		<property name="serverutils.bin.dir" value="${bin.config.dir}/serverutils"/>
		<property name="serverutils.bin.lib.dir" value="${serverutils.bin.dir}/lib"/>

		<property name="webservice.obj.dir" value="${obj.config.dir}/webservice"/>
		<property name="webservice.lib.dir" value="${webservice.obj.dir}/WEB-INF/lib"/>
		<property name="webservice.bin.dir" value="${bin.config.dir}/webservice"/>
							
		<patternset id="parser.sources">
			<include name="common/*.cpp"/>
			<include name="csharp/*.cpp"/>
			<include name="java/*.cpp"/>
		</patternset>		
	</target>


	<target name="parser.util" depends="init">	

		<mkdir dir="${parser.bin.dir}"/>
		<mkdir dir="${parser.obj.dir}"/>

		<cc
		 name="${cpp.compiler}"
		 outtype="executable"
		 rtti="true"
		 exceptions="true"
		 objdir="${parser.obj.dir}"
		 debug="${debug}"
		 runtime="${cc.runtime.libtype}"
		 optimize="speed"
		 multithreaded="true"
		 outfile="${parser.obj.dir}/parserutil">
			<includepath location="${icu.include.dir}"/>
			<fileset dir="${parser.src.dir}">
				<include name="parserutil/*.cpp"/>
				<patternset refid="parser.sources"/>
			</fileset>
			<linker name="${cpp.linker}">
				<libset type="shared" dir="${icu.lib.dir}" libs="${icu.libs}"/>
			</linker>
		</cc>

		<copy todir="${parser.bin.dir}">
			<fileset dir="${icu.lib.dir}">
				<include name="*${shlib.ext}"/>
			</fileset>
		</copy>

		<copy file="${parser.obj.dir}/parserutil${exec.ext}" todir="${parser.bin.dir}"/>
	</target>	


	<target name="parser.lib" depends="init">	

		<mkdir dir="${backend.bin.dir}"/>
		<mkdir dir="${parser.obj.dir}"/>

		<cc
		 name="${cpp.compiler}"
		 outtype="shared"
		 rtti="true"
		 exceptions="true"
		 objdir="${parser.obj.dir}"
		 debug="${debug}"
		 runtime="${cc.runtime.libtype}"
		 optimize="speed"
		 multithreaded="true"
		 outfile="${parser.obj.dir}/parserlib">
			<includepath location="${icu.include.dir}"/>
			<includepath location="${jni.common.dir}"/>
			<includepath location="${jni.os.dir}"/>
			<fileset dir="${parser.src.dir}">
				<include name="parserlib/*.cpp"/>
				<patternset refid="parser.sources"/>
			</fileset>
			<linker name="${cpp.linker}">
				<libset type="shared" dir="${icu.lib.dir}" libs="${icu.libs}"/>
			</linker>
		</cc>

		<copy todir="${backend.bin.dir}">
			<fileset dir="${icu.lib.dir}">
				<include name="*${shlib.ext}"/>
			</fileset>
			<fileset dir="${parser.obj.dir}">
				<include name="${lib.prefix}parserlib${shlib.ext}"/>
			</fileset>
		</copy>
	</target>	

	
	<target name="parser.tools" depends="init">
		
		<mkdir dir="${tools.bin.dir}"/>
		<mkdir dir="${tools.obj.dir}"/>
			
		<cc
		   name="${cpp.compiler}"
	 	   outtype="executable"
		   objdir="${tools.obj.dir}"
		   debug="${debug}"
		   runtime="${cc.runtime.libtype}"
		   outfile="${tools.bin.dir}/bnf2xsd">
			<fileset dir="${parser.tools.dir}/bnf2xsd">
				<include name="*.cpp"/>
			</fileset>
			<linker name="${cpp.linker}"/>
		</cc>
		
		<cc
		   name="${cc.compiler}"
		   outtype="executable"
		   objdir="${tools.obj.dir}"
		   debug="${debug}"
		   runtime="${cc.runtime.libtype}"
		   outfile="${tools.bin.dir}/jikespg">
			<fileset dir="${parser.tools.dir}/jikespg">
				<include name="*.c"/>
			</fileset>
			<linker name="${cc.linker}"/>
		</cc>
		
		<cc
		   name="${cpp.compiler}"
		   outtype="executable"
		   objdir="${tools.obj.dir}"
		   debug="${debug}"
		   runtime="${cc.runtime.libtype}"
		   outfile="${tools.bin.dir}/bnf2xsd">
			<fileset dir="${parser.tools.dir}/bnf2xsd">
				<include name="*.cpp"/>
			</fileset>
			<linker name="${cpp.linker}"/>
		</cc>
		
		<cc
		   name="${cpp.compiler}"
		   outtype="executable"
		   objdir="${tools.obj.dir}"
		   debug="${debug}"
		   runtime="${cc.runtime.libtype}"
		   outfile="${tools.bin.dir}/gperf">
			<fileset dir="${parser.tools.dir}/gperf">
				<include name="*.c"/>
				<include name="*.cc"/>
			</fileset>
			<linker name="${cpp.linker}"/>
		</cc>		
		
	</target>


	<target name="parser.test.java" depends="init, parser.util">
		<mkdir dir="${parser.testoutput.dir}"/>		
		<delete>
			<fileset dir="${parser.testoutput.dir}" includes="*.log"/>
		</delete>	

		<echo message="Running parser test for Java 1.4 ..."/>
		<apply executable="${parser.bin.dir}/parserutil" output="${parser.testoutput.dir}/java14test.log" append="true" failonerror="false" skipemptyfilesets="true">
			<arg value="-j"/>
			<srcfile/>
			<fileset dir="${parser.test.dir}">
				<include name="java14/**/*.java"/>						
			</fileset>
		</apply>

		<echo message="Running parser test for Java 1.5 ..."/>
		<apply executable="${parser.bin.dir}/parserutil" output="${parser.testoutput.dir}/java15test.log" append="true" failonerror="false" skipemptyfilesets="true">
			<arg value="-j5"/>
			<srcfile/>
			<fileset dir="${parser.test.dir}">
				<include name="java15/**/*.java"/>						
			</fileset>
		</apply>
	</target>


	<target name="parser.test.csharp" depends="init, parser.util">
		<mkdir dir="${parser.testoutput.dir}"/>		
		<delete>
			<fileset dir="${parser.testoutput.dir}" includes="*.log"/>
		</delete>	

		<echo message="Running parser test for CSharp 1.1 ..."/>
		<apply executable="${parser.bin.dir}/parserutil" output="${parser.testoutput.dir}/csharptest.log" append="true" failonerror="false" skipemptyfilesets="true">
			<arg value="-cs"/>
			<srcfile/>
			<fileset dir="${parser.test.dir}">
				<include name="csharp/**/*.cs"/>						
			</fileset>
		</apply>

		<echo message="Running parser test for CSharp 2.0 ..."/>
		<apply executable="${parser.bin.dir}/parserutil" output="${parser.testoutput.dir}/csharp2test.log" append="true" failonerror="false" skipemptyfilesets="true">
			<arg value="-cs2"/>
			<srcfile/>
			<fileset dir="${parser.test.dir}">
				<include name="csharp2/**/*.cs"/>						
			</fileset>
		</apply>
	</target>


	<target name="backend.core" depends="init">
		<mkdir dir="${backend.bin.dir}"/>
		<mkdir dir="${backend.class.dir}"/>

		<javac
		 srcdir="${client.src.dir}"
		 destdir="${backend.class.dir}"
		 source="${java.source.vm}"
		 target="${java.target.vm}"
		 debug="${debug}"
		 optimize="on"
		 classpath="${xfire.lib.dir}/xfire-core-1.2.2.jar"
		 includes="com/sourcedimensions/ws/provider/*.java"
		/>
			  

		<javac
		 srcdir="${backend.core.dir}"
		 destdir="${backend.class.dir}"
		 source="${java.source.vm}"
		 target="${java.target.vm}"
		 debug="${debug}"
		 optimize="on"
		 classpath="${hibernate.lib.dir}/hibernate3.jar;${xfire.lib.dir}/xfire-core-1.2.2.jar"
		 excludes="**/*.xml"
		/>

		<copy todir="${backend.class.dir}">
			<fileset dir="${backend.core.dir}">
				<include name="mapping/**/*.hbm.xml"/>
				<include name="schema/*.xsd"/>
				<include name="*.cfg.xml"/>
				<include name="**/*.gif"/>
				<include name="**/*.png"/>
			</fileset>
		</copy>

		<path id="backend.jars.depend">
			<fileset dir="${hibernate.lib.dir}">
				<include name="*.jar"/>
			</fileset>
			<fileset dir="${jdbc.lib.dir}">
				<include name="*.jar"/>
			</fileset>
			<fileset dir="${xfire.lib.dir}">
				<include name="*.jar"/>
			</fileset>
		</path>
		
		<pathconvert property="backend.jars.classpath" refid="backend.jars.depend" pathsep=" ">
			<flattenmapper/>
		</pathconvert>

		<jar destfile="${backend.bin.dir}/backend.jar" basedir="${backend.class.dir}">
			<manifest>
				<attribute name="Main-Class" value="com.sourcedimensions.server.sys.profile.adminutil.AdminUtil"/>
				<attribute name="Class-Path" value="${backend.jars.classpath}"/>
			</manifest>
		</jar>

		<copy todir="${backend.bin.dir}">
			<fileset dir="${hibernate.lib.dir}">
				<include name="*.jar"/>
			</fileset>
			<fileset dir="${jdbc.lib.dir}">
				<include name="*.jar"/>
			</fileset>
			<fileset dir="${xfire.lib.dir}">
				<include name="*.jar"/>
			</fileset>
			<fileset dir="${icu.lib.dir}">
				<include name="*${shlib.ext}"/>
			</fileset>
			<fileset dir="${parser.obj.dir}">
				<include name="${lib.prefix}parserlib${shlib.ext}"/>
			</fileset>
			<fileset dir="${backend.core.dir}">
				<include name="*.properties"/>
			</fileset>
		</copy>

	</target>

	<target name="server.utils" depends="backend.core">
		<mkdir dir="${serverutils.bin.dir}"/>
		<mkdir dir="${serverutils.bin.lib.dir}"/>

		<copy todir="${serverutils.bin.lib.dir}">
			<fileset dir="${backend.bin.dir}">
				<include name="*.jar"/>
				<include name="*${shlib.ext}"/>
				<include name="*.properties"/>
			</fileset>
		</copy>	

		<copy todir="${serverutils.bin.dir}">
			<fileset dir="${backend.core.dir}">
				<include name="*.cmd"/>
			</fileset>
		</copy>
	</target>

	<target name="webservice" depends="backend.core">
		<mkdir dir="${webservice.obj.dir}"/>
		<mkdir dir="${webservice.lib.dir}"/>
		<mkdir dir="${webservice.bin.dir}"/>
		
		<copy todir="${webservice.lib.dir}">
			<fileset dir="${backend.bin.dir}">
				<include name="*.jar"/>
				<include name="*${shlib.ext}"/>
			</fileset>
		</copy>		

		<copy todir="${webservice.obj.dir}">
			<fileset dir="${backend.core.dir}">
				<include name="WEB-INF/**/*.xml"/>
			</fileset>
		</copy>

		<war destfile="${webservice.bin.dir}/source-dimensions.war" webxml="${webservice.obj.dir}/WEB-INF/web.xml">
			<fileset dir="${webservice.obj.dir}">
				<exclude name="WEB-INF/web.xml"/>
			</fileset>
		</war>
		
	</target>


	<target name="all" depends="parser.util, parser.lib, parser.tools, server.utils, webservice"/>


	<target name="clean" depends="init">
		<delete dir="${obj.dir}"/>
		<delete dir="${bin.dir}"/>
	</target>

</project>