debug=true
debug.cpp=false

java.source.vm=1.5
java.target.vm=1.5

parser.test.dir=./../testsources
parser.test.dir.java=${parser.test.dir}/java14
parser.test.dir.java5=${parser.test.dir}/java15
parser.test.dir.cs=${parser.test.dir}/csharp
parser.test.dir.cs2=${parser.test.dir}/csharp2
parser.testoutput.dir=${parser.test.dir}

tomcat.home.dir=C:/Program Files/Apache Software Foundation/Tomcat 6.0