### set log levels - for more verbose logging change 'info' to 'debug' ###
# log4j.rootLogger=info, stdout, SQL_APPENDER 
# log4j.logger.org.hibernate=info

### log messages to stdout ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

### log messages to file ###
log4j.appender.SQL_APPENDER=org.apache.log4j.RollingFileAppender
log4j.appender.SQL_APPENDER.File=sql_trace.log
log4j.appender.SQL_APPENDER.MaxFileSize=25MB
log4j.appender.SQL_APPENDER.MaxBackupIndex=2
log4j.appender.SQL_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.SQL_APPENDER.layout.ConversionPattern=%p %t %c - %m%n

### log HQL query parser activity
# log4j.logger.org.hibernate.hql.ast.AST=debug

### log just the SQL
log4j.logger.org.hibernate.SQL=debug

### log JDBC bind parameters ###
# log4j.logger.org.hibernate.type=debug

### log schema export/update ###
# log4j.logger.org.hibernate.tool.hbm2ddl=debug

### log HQL parse trees
# log4j.logger.org.hibernate.hql=debug

### log cache activity ###
# log4j.logger.org.hibernate.cache=info

### log transaction activity
# log4j.logger.org.hibernate.transaction=debug

### log JDBC resource acquisition
# log4j.logger.org.hibernate.jdbc=debug

### enable the following line if you want to track down connection ###
### leakages when using DriverManagerConnectionProvider ###
# log4j.logger.org.hibernate.connection.DriverManagerConnectionProvider=trace