package com.sourcedimensions.client;

public interface IImageKeys 
{
	public final static String IMG_PROJECT = "icons/project.png";
	public final static String IMG_PARENT = "icons/parent.png";
	public final static String IMG_CHECKMARK = "icons/checkmark.png";
	public final static String IMG_CROSS = "icons/cross.png";
	public final static String IMG_SNAPSHOT_GROUP = "icons/snapshotgroup.png";
	public final static String IMG_FOLDER = "icons/folder.png";
	public final static String IMG_QUERY_GROUP = "icons/querygroup.png";
	public final static String IMG_SNAPSHOT = "icons/snapshot.png";
	public final static String IMG_SYMBOL_QUERY = "icons/symbol.png";
	public final static String IMG_GLOBAL_NAMESPACE_DECL = "icons/snapshot/global_namespace_decl.png";
	public final static String IMG_NAMESPACE_DECL = "icons/snapshot/namespace_decl.png";
	public final static String IMG_CLASS_DECL = "icons/snapshot/class_decl.png";
	public final static String IMG_ANONYM_CLASS_DECL = "icons/snapshot/anonym_class_decl.png";
	public final static String IMG_INTERFACE_DECL = "icons/snapshot/interface_decl.png";
	public final static String IMG_DELEGATE_DECL = "icons/snapshot/delegate_decl.png";
	public final static String IMG_ENUM_DECL = "icons/snapshot/enum_decl.png";
	public final static String IMG_STRUCT_DECL = "icons/snapshot/struct_decl.png";
	public final static String IMG_ANNOT_DECL = "icons/snapshot/annot_decl.png";
	public final static String IMG_ANONYM_METHOD_DECL = "icons/snapshot/anonym_method_decl.png";
	public final static String IMG_CONST_DECL = "icons/snapshot/const_decl.png";
	public final static String IMG_CONSTRUCTOR_DECL = "icons/snapshot/constructor_decl.png";
	public final static String IMG_DESTRUCTOR_DECL = "icons/snapshot/destructor_decl.png";
	public final static String IMG_ENUM_CONST_DECL = "icons/snapshot/enum_const_decl.png";
	public final static String IMG_EVENT_DECL = "icons/snapshot/event_decl.png";
	public final static String IMG_EVENT_ADD_DECL = "icons/snapshot/event_add_decl.png";
	public final static String IMG_EVENT_REMOVE_DECL = "icons/snapshot/event_remove_decl.png";
	public final static String IMG_FIELD_DECL = "icons/snapshot/field_decl.png";
	public final static String IMG_INDEXER_DECL	= "icons/snapshot/indexer_decl.png";
	public final static String IMG_INDEXER_GET_DECL = "icons/snapshot/indexer_get_decl.png";
	public final static String IMG_INDEXER_SET_DECL = "icons/snapshot/indexer_set_decl.png";
	public final static String IMG_METHOD_DECL = "icons/snapshot/method_decl.png";
	public final static String IMG_OPERATOR_DECL = "icons/snapshot/operator_decl.png";
	public final static String IMG_PROPERTY_DECL = "icons/snapshot/property_decl.png";
	public final static String IMG_PROPERTY_GET_DECL = "icons/snapshot/property_get_decl.png";
	public final static String IMG_PROPERTY_SET_DECL = "icons/snapshot/property_set_decl.png";
	public final static String IMG_LOCAL_DECL = "icons/snapshot/local_decl.png";
	public final static String IMG_PARAM_DECL = "icons/snapshot/param_decl.png";
	public final static String IMG_BASE_CLASS = "icons/snapshot/base_class.png";
	public final static String IMG_BASE_INTERFACE = "icons/snapshot/base_interface.png";
	public final static String IMG_CLASS_REF = "icons/snapshot/class_ref.png";
	public final static String IMG_INTERFACE_REF = "icons/snapshot/interface_ref.png";
	public final static String IMG_STRUCT_REF = "icons/snapshot/struct_ref.png";
	public final static String IMG_ENUM_REF = "icons/snapshot/enum_ref.png";
	public final static String IMG_DELEGATE_REF = "icons/snapshot/delegate_ref.png";
	public final static String IMG_FIXEDSIZEBUF_DECL = "icons/snapshot/fixedsizebuf_decl.png";
	public final static String IMG_INIT_BLOCK = "icons/snapshot/init_block.png";
}
